services:

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
      MSSQL_DB_NAME: 'PedidosDb'
    ports: 
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
        - app-network
    
  ambev-api:
    container_name: ambev-pedidos-api
    build:
        context: .
        dockerfile: Ambev.Pedidos.API/Dockerfile
    ports:
        - "5000:80"
    depends_on:
        - mssql
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=PedidosDb;User Id=sa;Password=Passw0rd;TrustServerCertificate=True
    networks:
        - app-network
networks:
    app-network:
        driver: bridge